### ISSUE TITLE
travis CI builds are failing for Kitura-Redis

### ISSUE THREAD

**Issue by BDHernand** [Kitura/Kitura-redis#18] opened 2016-08-01 17:20 UTC
The test cases are failing:

Test Case 'TestBasicCommands.test_setAndGet' started at 14:11:30.175
/root/Kitura-Redis/Tests/SwiftRedis/TestBasicCommands.swift:48: error: TestBasicCommands.test_setAndGet : XCTAssertNil failed: "<NSError: 0x000000000094da30>" - Error: Not connected to Redis server
/root/Kitura-Redis/Tests/SwiftRedis/TestBasicCommands.swift:62: error: TestBasicCommands.test_setAndGet : XCTAssertNil failed: "<NSError: 0x000000000094f5b0>" - Error: Not connected to Redis server
/root/Kitura-Redis/Tests/SwiftRedis/TestBasicCommands.swift:63: error: TestBasicCommands.test_setAndGet : XCTAssertTrue failed - Failed to set test1
/root/Kitura-Redis/Tests/SwiftRedis/TestBasicCommands.swift:66: error: TestBasicCommands.test_setAndGet : XCTAssertNil failed: "<NSError: 0x000000000094f740>" - Error: Not connected to Redis server
fatal error: unexpectedly found nil while unwrapping an Optional value

are the errors

**Comment by ianpartridge** [comment] 2016-08-01 18:15
Can you link to the failing build?

The most recent I see is https://travis-ci.org/IBM-Swift/Kitura-redis/builds/148125019 which passed.

**Comment by youming-lin** [comment] 2016-08-01 18:22
@ianpartridge @BDHernand linked me this build: https://travis-ci.org/BDHernand/Kitura-redis/jobs/148434752

**Comment by ianpartridge** [comment] 2016-08-01 18:26
@shmuelk this looks like IBM-Swift/Kitura#662

**Comment by youming-lin** [comment] 2016-08-01 18:43
@BDHernand The tests pass: https://travis-ci.org/IBM-Swift/Kitura-redis/builds/148955983. Can you restart that failing test and try again?

**Comment by ianpartridge** [comment] 2016-08-11 20:29
Closing as very likely a duplicate of IBM-Swift/Kitura#662

**Closed as completed by ianpartridge** 2016-08-11 20:29 UTC
